#!/bin/bash

if [[ ! $# -eq 2 ]]; then
    echo "Two arguments needed: Year and day."
    exit 1
fi

# Set up paths
BASE_PATH="/home/$USER/Projects/advent-of-code"
YEAR="$1"
DAY="$2"

# Check if directory for year exists, otherwise this can't continue
if [ ! -d "$BASE_PATH/$YEAR" ]; then
    echo "$BASE_PATH/$YEAR"
    echo "Directory for year does not exist!"
    exit 1
fi
(
    cd "$BASE_PATH/$YEAR"
    # If file doesn't exist, but a template is available, create file from template
    if [ ! $DAY -eq "00" -a ! -f "src/solutions/day$DAY.zig" -a -f "src/solutions/day00.zig" ]; then
        cp -HLr "src/solutions/day00.zig" "src/solutions/day$DAY.zig"
        zig build update-solutions
    fi

    # input file doesn't exist, try to download it
    if [ ! -f "input/$DAY.txt" ]; then
        curl "https://adventofcode.com/20$YEAR/day/$(sed 's/^0*//' <<<$DAY)/input" -H "Cookie: session=$(cat .session.txt)" -o "input/$DAY.txt"
    fi

    ZELLIJ_SESSION_NAME="advent-of-code.$YEAR"

    # Delete old, exited session, so zellij doesn't revive it and we get a fresh session
    zellij list-sessions | grep "$ZELLIJ_SESSION_NAME" | grep EXITED
    greprc=$?
    if [[ $greprc -eq 0 ]]; then
        zellij delete-session "$ZELLIJ_SESSION_NAME"
    fi

    # Reattach dispatched sessions, since those were probably dispatched on purpose for e.g.
    # unsaved changes. Otherwise create fresh session with layout.
    zellij list-sessions | grep "$ZELLIJ_SESSION_NAME"
    greprc=$?
    if [[ $greprc -eq 0 ]]; then
        zellij attach "$ZELLIJ_SESSION_NAME"
    else
        export DAY=$DAY
        zellij -s "$ZELLIJ_SESSION_NAME" -n zellij.kdl
    fi
)
