#!/bin/bash
echo "Test successful!"

while sleep 0.1
do 
  find -L src/main.zig src input -type f | entr -ds 'clear; tmp=${0##*/}; tmp=${tmp//[!0-9]/}; tmp=${tmp:=$DAY}; timeout 30 zig build test-day${tmp} && echo -e "\n\033[0;33mDEBUG BUILD:\033[0m" && (timeout 60 zig build run -- ${tmp} || echo -e "TIMEOUT") && echo -e "\n\033[1;32mRELEASE BUILD:\033[0m" && zig build run -Doptimize=ReleaseSafe -- ${tmp}'
done
